id: I9D9D2392
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T17:34:52+00:00'
last_modified: '2022-06-08T05:40:06.911022+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25184
  title: བོད་ལུགས་སྨན་སྦྱོར་རིག་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4F32:
      image_group_id: I5698
      title: ''
      total_pages: 376
      order: 1
      base_file: 4F32.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
