id: P006618
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W25184
  title: བོད་ལུགས་སྨན་སྦྱོར་རིག་པ
  author: ''
  volumes:
    3002871cb59f44fc847110b90abc87a7:
      image_group_id: I5698
      title: ''
      volume_number: 1
      total_pages: 376
      base_file: v001.txt
